development:
  secret_key_base: <%= ENV["DEV_SECRET_KEY_BASE"] %>

  mailer:
    authentication: <%= ENV["MAILER_AUTHENTICATION"] %>
    address: <%= ENV["MAILER_ADDRESS"] %>
    username: <%= ENV["MAILER_USERNAME"] %>
    password: <%= ENV["MAILER_PASSWORD"] %>

  recaptcha:
    site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
    secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

  send_in_blue:
    api_key: <%= ENV["SEND_IN_BLUE_API_KEY"] %>

  stripe:
    publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
    secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
    client_id: <%= ENV["STRIPE_CLIENT_ID"] %>

  twilio:
    sid: <%= ENV["TWILIO_SID"] %>
    token: <%= ENV["TWILIO_TOKEN"] %>
    number: <%= ENV["TWILIO_NUMBER"] %>

test:
  secret_key_base: <%= ENV["TEST_SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  recaptcha:
    site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
    secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

  send_in_blue:
    api_key: <%= ENV["SEND_IN_BLUE_API_KEY"] %>

  stripe:
    publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
    secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
    client_id: <%= ENV["STRIPE_CLIENT_ID"] %>

  twilio:
    sid: <%= ENV["TWILIO_SID"] %>
    token: <%= ENV["TWILIO_TOKEN"] %>
    number: <%= ENV["TWILIO_NUMBER"] %>

staging:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

    recaptcha:
      site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
      secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

    send_in_blue:
      api_key: <%= ENV["SEND_IN_BLUE_API_KEY"] %>

    stripe:
      publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
      secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
      client_id: <%= ENV["STRIPE_CLIENT_ID"] %>

    twilio:
      sid: <%= ENV["TWILIO_SID"] %>
      token: <%= ENV["TWILIO_TOKEN"] %>
      number: <%= ENV["TWILIO_NUMBER"] %>
